# Site Settings
title: 생각정리
email: dydtjd0245@gmail.com
description: 이것저것 정리하는 블로그
baseurl: ""
url: ""
#url: "https://kimyongsung.github.io"
#google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: kys0213
user_description: 자바 백엔드 개발자
disqus_username: kysblog

# Social Media
# Remove the item if you don't need it
github_username: KimYongSung
facebook_username: 100024155509064
#twitter_username: twitter_username
instagram_username: kim_yongsoung
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
